### ISSUE TITLE
Test suite does not compile with Clang 13.1

### ISSUE THREAD

**Issue by gareth-rees** [Ravenbrook/mps#78]
```
$ clang --version
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ make -f xca6ll.gmk VARIETY=cool testrun
zmess.c:151:7: error: variable 'found' set but not used [-Werror,-Wunused-but-set-variable]
  int found = 0;
      ^
1 error generated.
```
