### ISSUE TITLE
MPS snapshot fails to build on Debian/Sid/x86-64 with GCC 8.3

### ISSUE THREAD

**Issue by bstarynk** [Ravenbrook/mps#6]

**Comment by bstarynk** [comment]
with GCC 8.3, on Linux/Debian/Sid/x86-64 MPS commit 7278e92446a99ce7 fails to build after a ./configure && make with the following errors:

```

lii6gc: lii6gc/cool/format.o
format.c: In function ‘FormatDescribe’:
format.c:236:31: error: cast between incompatible function types from ‘mps_fmt_scan_t’ {aka ‘int (*)(struct mps_ss_s *, void *, void *)’} to ‘void * (*)(void)’ [-Werror=cast-function-type]
                "  scan $F\n", (WriteFF)format->scan,
                               ^
format.c:237:31: error: cast between incompatible function types from ‘mps_fmt_skip_t’ {aka ‘void * (*)(void *)’} to ‘void * (*)(void)’ [-Werror=cast-function-type]
                "  skip $F\n", (WriteFF)format->skip,
                               ^
format.c:238:31: error: cast between incompatible function types from ‘mps_fmt_fwd_t’ {aka ‘void (*)(void *, void *)’} to ‘void * (*)(void)’ [-Werror=cast-function-type]
                "  move $F\n", (WriteFF)format->move,
                               ^
format.c:239:34: error: cast between incompatible function types from ‘mps_fmt_isfwd_t’ {aka ‘void * (*)(void *)’} to ‘void * (*)(void)’ [-Werror=cast-function-type]
                "  isMoved $F\n", (WriteFF)format->isMoved,
                                  ^
format.c:240:30: error: cast between incompatible function types from ‘mps_fmt_pad_t’ {aka ‘void (*)(void *, long unsigned int)’} to ‘void * (*)(void)’ [-Werror=cast-function-type]
                "  pad $F\n", (WriteFF)format->pad,
                              ^
cc1: all warnings being treated as errors
make[3]: *** [comm.gmk:618: lii6gc/cool/format.o] Error 1
make[3]: Leaving directory '/SrcBasile/Libs/mps/code'
make[2]: *** [comm.gmk:391: target] Error 2
make[2]: Leaving directory '/SrcBasile/Libs/mps/code'
make[1]: *** [comm.gmk:363: mps.a] Error 2
make[1]: Leaving directory '/SrcBasile/Libs/mps/code'
make: *** [Makefile:28: build-via-make] Error 2
```

I don't exactly know how to fix that easily. I guess that the compilation flags to GCC should be less strict.


The point is that GCC 8 has more warnings than previous versions of GCC, and you should want to disable some of them (e.g. not handling them as serious errors).

**Comment by bstarynk** [comment]
The attached diff is a fix to that issue. Basically replacing every cast `(WriteFF)` with `(WriteFF)(void*)` and using `CFLAGSCOMPILERSTRICT := -std=c99` in `code/gc.gmk` file

[mps-7278e92446a99ce7dc1.diff.gz](https://github.com/Ravenbrook/mps/files/2960580/mps-7278e92446a99ce7dc1.diff.gz)

**Comment by gareth-rees** [comment]
Thanks for the report! This was fixed by commit afda9bd35d -- the MPS now builds without warnings using GCC 8.4.0.

The MPS is strict about warnings because we recommend that users build their own sources against the MPS sources in order to allow the compiler to inline MPS operations into client code. But this means the MPS has to compile whatever warning options are in force in the user's build system.
