### ISSUE TITLE
Manuals don't build with Sphinx 2.2.1, create untracked file

### ISSUE THREAD

**Issue by gareth-rees** [Ravenbrook/mps#12]
Building the MPS manuals with Sphinx 2.2.1 fails with one warning and one error:
```
$ make -C manual html
sphinx-build -b html -d ./doctrees   source ./html
Running Sphinx v2.2.1
/Users/gdr/github.com/mps/manual/source/extensions/mps/__init__.py:23: RemovedInSphinx30Warning: sphinx.locale.versionlabels is deprecated. Please use sphinx.domains.changeset.versionlabels instead.
  versionlabels['deprecatedstarting'] = "Deprecated starting with version %s"

Exception occurred:
  File "/Users/gdr/github.com/mps/manual/source/extensions/mps/designs.py", line 147, in convert_updated
    app.info(bold('converting MPS design documents'))
AttributeError: 'Sphinx' object has no attribute 'info'
```
The warning seems to be fixable by following the instructions:
```
from sphinx.domains.changeset import versionlabels
```
The error can be fixed by using the Sphinx logging interface, that is:
```
from sphinx.util import logging
logger = logging.getLogger(__name__)
```
and then using `logger.info()` instead of `app.info()`.

Additionally, building the manuals creates an untracked file (manual/source/design/monitor.png). This needs to be added to manual/.p4ignore.
