### ISSUE TITLE
Restore Darwin PowerPC

### ISSUE THREAD

**Issue by barracuda156** [Ravenbrook/mps#278]
@rptb1 @gareth-rees 
Could we restore PowerPC support? It evidently existed at some point: https://github.com/Ravenbrook/mps/tree/branch/2007-12-19/vmarenagrow
However, the present version of configure is unaware of ppc and ppc64 on macOS.

**Comment by gareth-rees** [comment]
The problem with restoring support for the xcppgc platform is—how would we test it? The last PowerPC Macintoshes were manufactured in 2006, or thereabouts, so I guess we'd have to use an emulator. The last version of OS X to support PowerPC was 10.5 (Leopard) which we no longer support either, so this would be a lot of work, I think too much for us to realistically undertake it.

However, if you already have the hardware and the operating system, it would not be too difficult to implement your own support for this platform. The [Porting the MPS](https://memory-pool-system.readthedocs.io/en/latest/topic/porting.html) chapter of the manual has an outline for how to do it.

I would start by copying the xci6gc implementation, where the only Intel-specific modules are the Protection Mutator Context modules (prmci6.c and prmcxci6.c), and most of the functions are only used for optimizations, so you can start with the generic versions in prmcanan.c, leaving you (I think) only needing to implement the function `MutatorContextSP` in the new module prmcxcpp.c.

**Comment by rptb1** [comment]
The PowerPC platform was removed in Perforce changelist 178908 on 2021-08-12 which corresponds to This corresponds to Git commit 9e1492305021f675f0beb45b5dec99dbe97f94dd .  You can see there what was removed. The changelist resolved these issues:

> job000599 on 2013/03/19 by nb *closed*
> 
> 	MPS doesn't build on Mac OS X 10.2
> 
> job000601 on 2013/03/19 by rb *closed*
> 
> 	MPS compile fails under Mac OS X 10.2
> 
> job001146 on 2013/03/19 by drj *closed*
> 
> 	MPS does not implement a stack scanner for OS X / PowerPC
> 
> job001543 on 2013/03/19 by rhsk *closed*
> 
> 	MPS mpsicv (test) on OS X does not use reg&stack scanner.
> 
> job001544 on 2013/03/19 by rhsk *closed*
> 
> 	MPS mpsicv coverage test source does not have ifndef CONFIG_PF_XCI3GC
> 
> job001634 on 2014/04/12 by drj *closed*
> 
> 	MPS fails under Rosetta.
> 
> job001635 on 2012/08/15 by drj *closed*
> 
> 	On Unix, signal handler is not installed correctly.
> 
> job001714 on 2013/03/19 by rhsk *closed*
> 
> 	MPS xcppgc (Mac OS X PowerPC) is built with outdated compiler flags

You can look up the job details, which include some analysis of issues, at e.g. https://www.ravenbrook.com/project/mps/issue/job000599/ .

It's quite likely that you can reinstate these with little to no modification but you'll also be reinstating those issues!

macOS PowerPC was a combination I used for many years on my desktop to develop and debug the MPS, but it was never a supported platform in deployment, so it has not been exposed and hardened to real world use.

If you're thinking of a different PowerPC target, I'd be interested to hear about it.  I'm also interested in why you want this.

If you get it working perhaps you could note details here for other people.

Thanks!

**Comment by barracuda156** [comment]
@rptb1 Thank you, this is very informative!

Yes, I consider macOS PowerPC myself, though admittedly Linux and possibly FreeBSD have a wider audience. Why – well, I have hardware, and late G5 are nice to use even today, and also we support PowerPC systems in Macports.

**Comment by rptb1** [comment]
Please do ask questions here if you decide to hack on this. We'll try to answer, though our resources are limited.
